export const mockData = {
  rows: [
    {
      id: 1,
      name: 'Mike',
      position: 'Cook',
      department: 'Center',
      ratePerHour: 1,
      foodExpenses: 400,
      award1: 466,
      award2: 9568,
      banquetPercent: 23,
      tips1: 3335,
      tips2: 32434,
      totalSalary: 3455345435,
      salary: 45345,
      fine: 4,
      medicalBook: 'yes',
      tax: 33,
      additionalResp: 232,
      prepaidExpense: 23423,
      workDay: 'yes',
      workNight: 'yes',
      work: [
        {
          day: '1',
          hour: '3,5',
        },
        {
          day: '2',
          hour: '3,5',
        },
        {
          day: '3',
          hour: '3,5',
        },
        {
          day: '4',
          hour: '3,5',
        },
        {
          day: '5',
          hour: '3,5',
        },
        {
          day: '6',
          hour: '3,5',
        },
        {
          day: '7',
          hour: '',
        },
        {
          day: '8',
          hour: '3,5',
        },
        {
          day: '9',
          hour: '',
        },
        {
          day: '10',
          hour: '',
        },
      ],
    },
  ],
  columns: [
    {
      field: 'name',
      headerName: 'Имя',
      width: 100,
      sortable: true,
      filterable: true,
    },
    {
      field: 'totalHours',
      headerName: 'итог',
      width: 100,
      sortable: true,
      filterable: true,
      editable: true,
    },
    {
      field: 'day',
      headerName: 'день',
      width: 100,
    },
    {
      field: 'night',
      headerName: 'ночь',
      width: 100,
    },
    {
      field: 'ratePerHour',
      headerName: 'Ставка в час',
      width: 100,
      sortable: true,
      filterable: true,
    },
    {
      field: 'totalSalary',
      headerName: 'Итого ЗП, руб',
      width: 100,
      sortable: true,
      filterable: true,
    },
    {
      field: 'payments(waitress/marshals)',
      headerName: 'Выплаты (маршалы/официанты)',
      width: 100,
      sortable: true,
      filterable: true,
    },
    {
      field: 'prepaidExpense',
      headerName: 'Аванс',
      width: 100,
      sortable: true,
      filterable: true,
    },
    {
      field: 'additionalResp',
      headerName: 'Доп. обязанности, руб',
      width: 100,
      sortable: true,
      filterable: true,
    },
    {
      field: 'fine',
      headerName: 'Штрафы',
      width: 100,
      sortable: true,
      filterable: true,
    },
    {
      field: 'medicalBook',
      headerName: 'Мед. книжка',
      width: 100,
      sortable: true,
      filterable: true,
    },
    {
      field: 'tax',
      headerName: 'Налоговый вычет',
      width: 100,
      sortable: true,
      filterable: true,
    },
    {
      field: 'tips1',
      headerName: 'Чаевые Ч1',
      width: 100,
      sortable: true,
      filterable: true,
    },
    {
      field: 'tips2',
      headerName: 'Чаевые Ч2',
      width: 100,
      sortable: true,
      filterable: true,
    },
    {
      field: 'banquetPercent',
      headerName: 'Проценты за банкет',
      width: 100,
      sortable: true,
      filterable: true,
    },
    {
      field: 'award1',
      headerName: 'Премия 1',
      width: 100,
      sortable: true,
      filterable: true,
    },
    {
      field: 'award2',
      headerName: 'Премия 2',
      width: 100,
      sortable: true,
      filterable: true,
    },
    {
      field: 'foodExpenses',
      headerName: 'Расходы на продукты',
      width: 100,
      sortable: true,
      filterable: true,
    },
    {
      field: 'totalSalary',
      headerName: 'Итого ЗП, руб',
      width: 100,
      sortable: true,
      filterable: true,
    },
  ],
};
